### ISSUE TITLE
Add Path "derivationPath" to Wallet

### ISSUE THREAD

**Issue by dangell7** [MitchLang009/XRPKit#22]
On Xpring they use derivationPath. Is this the same thing as Path? I think it is. For trust lines and what not. What are your thoughts on this? I currently save it with the wallet info. And different wallets "could" have different paths.

**Comment by MitchLang009** [comment]
You mean for the wallet generation from a mnemonic? That means the mnemonic path, for example bip39, which is the implementation we have from https://github.com/yuzushioh/HDWalletKit/blob/d5566cfcf94c4a536719f72a15de11320016d659/HDWalletKit/Mnemonic.swift

Maybe we want to support other paths?  I need to read more about mnemonics to understand them better.

XRPL Paths are different: https://xrpl.org/paths.html

**Comment by MitchLang009** [comment]
Copying links for reference:

What we have: https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki
What we need:  https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki
Swift example: https://github.com/essentiaone/HDWallet

**Comment by MitchLang009** [comment]
XpringKit reference:

https://github.com/xpring-eng/xpring-common-js/blob/9d847a3df1f83956fb8df46fead31d9bae3fb6ba/src/wallet.ts#L77

**Comment by MitchLang009** [comment]
Swift implementations of BIP32/BIP44:
https://github.com/essentiaone/HDWallet/blob/develop/HDWalletKit/Wallet/PrivateKey.swift
https://github.com/goldennetwork/GoldenKeystore/blob/master/KeyDerivation.swift
https://github.com/yuzushioh/HDWalletKit/blob/master/HDWalletKit/HDPrivateKey.swift
